platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod "Koloda"
pod 'ActionSheetPicker-3.0'
pod 'RealmSwift'
pod 'SwiftyJSON', '~> 2.3.0'
pod 'IQKeyboardManager', '~> 3.3.2'